[build]
  publish = "dist"
#  functions = "functions/" # netlify dev uses this directory to scaffold and serve your functions

[functions]
  directory = "functions/"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "."
#[dev]
#  command = "yarn dev"
#  port = 8888
#  targetPort = 3000
#  publish = "dist"
